export const ADD_BOOKS = "ADD_BOOKS";
export const ADD_AUTHORS = "ADD_AUTHORS";
export const SET_BOOK_PREVIEW = "SET_BOOK_PREVIEW";
export const REMOVE_BOOK_PREVIEW = "REMOVE_BOOK_PREVIEW";
export const ADD_BOOK_TO_CART = "ADD_BOOK_TO_CART";
export const REMOVE_BOOK_FROM_CART = "REMOVE_BOOK_FROM_CART";
export const INCREASE_COUNT = "INCREASE_COUNT";
export const DECREASE_COUNT = "DECREASE_COUNT";
