export const SET_BOOK_PREVIEW = "SET_BOOK_PREVIEW";
export const REMOVE_BOOK_PREVIEW = "REMOVE_BOOK_PREVIEW";
export const ADD_BOOK_TO_CART = "ADD_BOOK_TO_CART";
export const REMOVE_BOOK_FROM_CART = "REMOVE_BOOK_FROM_CART";
